// 集中测试样本：后续测试只通过对象展开修改单一字段，避免每个测试复制一套漂移样本。
// 时间统一使用 2026-08-24T00:00:00Z。

import type { BFF主体, BFF简历, BFFOwnerJob, BFFOwnerIntention } from '../数据/BFF契约';
import type { 在招岗位 } from '../数据/类型';

export const BFF主体样本: BFF主体 = {
  subject_id: 'sub_1',
  roles: [{ role: 'candidate', status: 'active' }],
  last_used_role: 'candidate',
};

export const BFF简历样本: BFF简历 = {
  profile: {
    real_name: '沈亦舟',
    work_start_year: 2021,
    status: 'employed',
    current_education: null,
    graduation_year: null,
    gender: 'male',
    birth_year: 1998,
    birth_month: 6,
  },
  profile_revision: 2,
  summary: '优势',
  summary_revision: 1,
  skills: ['TypeScript'],
  skills_revision: 3,
  experiences: [
    {
      id: 'exp_1',
      company: '云衢',
      industry: { id: 'tax_i', display_name: '互联网' },
      title: '工程师',
      start_month: '2021-01',
      end_month: null,
      description: '平台',
      hidden: true,
      internship: false,
      revision: 4,
      projects: [],
    },
  ],
  educations: [
    {
      id: 'edu_1',
      institution: { id: 'ins_1', display_name: '复旦大学' },
      degree: '本科',
      major: { id: 'tax_m', display_name: '计算机科学' },
      start_month: '2017-09',
      end_month: '2021-06',
      revision: 2,
    },
  ],
  certificates: [{ id: 'cert_1', name: 'PMP', year: 2024, revision: 1 }],
  aggregate_revision: 9,
};

export const BFF岗位样本: BFFOwnerJob = {
  job_id: 'job_1',
  publisher_mode: 'direct',
  publisher_verification_status: 'unverified',
  hiring_organization_claim: { display_name: '云衢科技', legal_name: null },
  title: 'AI 产品实习生',
  recruitment_type: 'internship',
  category: { id: 'tax_product', display_name: '产品经理' },
  location: { id: 'loc_shanghai', display_name: '上海' },
  office_location: '张江路 1 号',
  workplace_mode: 'hybrid',
  salary_lower: 300,
  salary_upper: 500,
  salary_period: 'day',
  annual_salary_months: null,
  campus_cohort: null,
  internship_months: 3,
  onsite_days_per_week: 4,
  experience_requirement: 'none',
  education_requirement: 'bachelor',
  description: '参与产品工作',
  requirements: '在校生',
  keywords: ['Python'],
  private_screening_preferences: '',
  status: 'active',
  revision: 1,
  published_at: '2026-08-24T00:00:00Z',
  created_at: '2026-08-24T00:00:00Z',
  updated_at: '2026-08-24T00:00:00Z',
};

export const 页面岗位样本: 在招岗位 = {
  编号: 'job_1',
  名称: 'AI 产品实习生',
  薪资带: '300-500 元/天',
  状态: '在招',
  在谈数: 0,
  城市: '上海',
  办公地: '张江路 1 号',
  办公方式: '混合',
  招聘类型: '实习生',
  职位类别: '产品经理',
  筛选要求: '',
  经验要求: '不限',
  最低学历: '本科',
  职位描述: '参与产品工作',
  职位要求: '在校生',
  硬性条件: ['本科及以上'],
  职位关键词: ['Python'],
  加分关键词: ['课程项目'],
  实习月数: 3,
  每周天数: 4,
  实习转正: true,
  发布于: '2026-08-24',
};

export const BFF意向样本: BFFOwnerIntention = {
  intention_id: 'int_1',
  recruitment_type: 'internship',
  job_category: { id: 'tax_product', display_name: '产品经理' },
  primary_location: { id: 'loc_shanghai', display_name: '上海' },
  alternate_locations: [],
  industries: [],
  workplace_modes: ['hybrid'],
  compensation: { mode: 'range', lower: 300, upper: 500, annual_salary_months: null },
  salary_period: 'day',
  graduation_month: null,
  internship_months: 3,
  onsite_days_per_week: 4,
  exclusions: {
    alternate_weekend_work: 'unspecified',
    outsourcing_only: 'unspecified',
    onsite_only: 'unspecified',
    frequent_travel: 'unspecified',
  },
  private_preferences: '',
  status: 'active',
  revision: 1,
  created_at: '2026-08-24T00:00:00Z',
  updated_at: '2026-08-24T00:00:00Z',
};